require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'meetme' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'




  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'


  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNSecureStorage', :path => '../node_modules/rn-secure-storage'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'meetmeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'meetme-tvOS' do
  # Pods for meetme-tvOS

  target 'meetme-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
